### PR TITLE
Upgrade

### LINKED ISSUE #31: Suggestion: Use official release API to always get the latest stable release
Hello,

I recommend you use the official JSON API to always download the latest stable version: https://fossil.kd2.org/garradin/juvlist

This lists all current releases. You only need to extract the version from the file name and find out the latest one. Here is a quick and dirty example in JS:

```

fetch('./juvlist').then((r) => {
	r.json().then((list) => {
		let last;
		let selected;

		list.forEach((file) => {
			var v = file.name.match(/^garradin-(.*)\.tar\.bz2/);

			if (!v) {
				return;
			}

			if (!last || isNewerVersion(last, v[1])) {
				last = v[1];
				selected = file;
			}
		});

                console.log(`Latest release is ${last} available at: https://fossil.kd2.org/uv/${selected.name}`);
	});
});

```

That way you wouldn't have to update your package to change the URL and hash every time.

### PR DESCRIPTION
**Pull request by yalh76**
## Problem

- *Fix #31*

## Solution

- *Apply example_ynh*
- *Implement autoupdater*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
> nice, this will update the release with each new versions... Why the Install (private) seems Fail ?? Perhaps is not real ?

it's an issue on package_check when it use recents versions to lxd.
at the end it goes well on ci-apps

**Comment by rodinux** [comment]
Ok let's go .

**Pull request merged**
