### PR TITLE
upgrade to 1.1.27

### PR DESCRIPTION
**Pull request by rodinux**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by rodinux** [comment]
!testme

**Comment by rodinux** [comment]
review required, who can approuve ? @alexAubin @BenoitCier @fflorent @frju365 @ericgaspar @zamentur ??

**Review by fflorent — APPROVED** [review]
Lgtm

**Comment by rodinux** [comment]
> Lgtm

Thanks, I can't merge at once... need 1 approving by a reviewer...

**Review by ericgaspar — APPROVED** [review]

**Comment by rodinux** [comment]
Yep! celefeu

**Pull request merged**
