### PR TITLE
update to 1.1.25

### PR DESCRIPTION
**Pull request by rodinux**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by rodinux** [comment]
Oups, 
I have an error tryng update garradin on a local development test (virtualbox). After upgrading I see this error message:
# PHP error
## Declaration of Garradin\Entities\Web\Page::load(array $data): void must be compatible with KD2\DB AbstractEntity::load(array $data): KD2\DB\AbstractEntity
### in .../include/lib/Garradin/Entities/Web/**Page.php**:__109__

```
105
106		return $this->_file;
107	}
108
109	public function load(array $data): void
110	{
111		parent::load($data);
112
113		if ($this->file() && $this->file()->modified > $this->modified) {
```

**Comment by rodinux** [comment]
I discover this error is produced with the public Web site on Garradin, when calling Page.php. If the application don't use a public Web site, the upgrade match, expect the configuration for the Web site which return this error. 
So I suspect it is a problem with the nginx.conf.

**Comment by rodinux** [comment]
> Oups, I have an error tryng update garradin on a local development test (virtualbox). After upgrading I see this error message:
> # PHP error
> ## Declaration of Garradin\Entities\Web\Page::load(array $data): void must be compatible with KD2\DB AbstractEntity::load(array $data): KD2\DB\AbstractEntity
> ### in .../include/lib/Garradin/Entities/Web/**Page.php**:**109**
> 
> ```
> 105
> 106		return $this->_file;
> 107	}
> 108
> 109	public function load(array $data): void
> 110	{
> 111		parent::load($data);
> 112
> 113		if ($this->file() && $this->file()->modified > $this->modified) {
> ```

The developer found the error, it was a packaging error and it is resolved, fine !

**Comment by rodinux** [comment]
!testme

**Review by ericgaspar — APPROVED** [review]

**Pull request merged**
