### PR TITLE
upgrade to 1.1.28

### PR DESCRIPTION
**Pull request by rodinux**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by rodinux** [comment]
!testme

**Comment by rodinux** [comment]
Perhaps I will try merge with a branch to be compatible with Yunohost 11.0.9 here https://github.com/YunoHost-Apps/garradin_ynh/tree/yunohost_debian11, is it a good idea ?

**Comment by rodinux** [comment]
Ok, I try migrate my virtualbox yunohost to test the update with bullseye...

**Comment by rodinux** [comment]
Hi, ok I tested an upgrade on a local Yunohost migrated to 11.0.9, it seems all good for me, I added also the module php-gnupg which permit crypt mails...
anyone to review and/or push the PR @ericgaspar ? @alexAubin @fflorent ? @frju365 ? @yalh76 ? @zamentur ?

**Review by yalh76 — APPROVED** [review]

**Comment by rodinux** [comment]
Thanks !

**Pull request merged**
