### PR TITLE
Fix permissions

### PR DESCRIPTION
**Pull request by tituspijean**
Fix the permissions on files. It looks like making `www-data` as group owner is required to have NGINX access the files.

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by tituspijean** [comment]
[Test Badge](https://ci.pijean.ovh/ci/job/39)

**Comment by tituspijean** [comment]
[Test Badge](https://ci.pijean.ovh/ci/job/40)

**Comment by tituspijean** [comment]
[Test Badge](https://ci.pijean.ovh/ci/job/40)

**Review by rodinux — APPROVED** [review]
Nice work, I agree.

**Pull request merged**
