### PR TITLE
Fix update 1.2.4

### PR DESCRIPTION
**Pull request by rodinux**
## Problem

- *Garradin is now called paheko*
- *The source package and the links for the source project changed with this new name paheko*
- *Since 1.2.4, the dev downgraded the default SQLite journal mode to TRUNCATE instead of WAL because it might have been a cause of corruption on some hosting providers using NFS. He don't think that Yunohost can use NFS, so we should set it back to WAL by adding the following line to config.local.php when installing const SQLITE_JOURNAL_MODE = 'WAL';*

## Solution

- *rename links and package sources with the new name paheko*
- *edit also the workflow updater.sh to have correct names and links*
- *edit the config.yunohost.local.php to keep the WAL sqlite*

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by rodinux** [comment]
!testme

**Comment by rodinux** [comment]
!testme

**Comment by rodinux** [comment]
!testme

**Comment by rodinux** [comment]
Ok, for me it is all right, nice release. 
I have tested this release on local machine, upgrading from stable branch, etc... all work nice.
I am just thinking about still using the name garradin-ynh or if should we change it to paheko_ynh, but it seems complicated to do...

**Comment by rodinux** [comment]
I am trying to make a repository paheko_ynh with a script for migration, but it doesn't work at once... https://github.com/YunoHost-Apps/paheko_ynh/pull/3

**Comment by rodinux** [comment]
Why here I have good results and not with the paheko package ???
!testme

**Comment by rodinux** [comment]
Hello, I need push this PR, please. Last time for this project which will be migrate to paheko...

**Review by ericgaspar — APPROVED** [review]

**Pull request merged**
