### PR TITLE
1.1.5

### PR DESCRIPTION
**Pull request by rodinux**
## Problem
- *fix permissive permission on www directory*

## Solution
- *change the permission recursive in www directory*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

### CODE REVIEW

**Comment by rodinux** [comment]
!testme

**Review by frju365 — APPROVED** [review]
Lgtm ans code review. I will perhaps do a manual test.

**Comment by rodinux** [comment]
@frju365 I haven't upgrade all the next release, for example now garradin is comming with a version 1.1.9... I am not sure with the permissions I have change to be more secure... I have a problem with the mails since these changes, perhaps it is necessary add a php module for php7.4 ? I am not sure...
If you can test manually and see how we can upgrade to the last version, it will be nice.

**Comment by rodinux** [comment]
Ok, je viens de tester la version 1.1.9, ça fonctionne semble-t-il...

**Comment by rodinux** [comment]
!testme

**Comment by rodinux** [comment]
upgrade to 1.1.10
!testme

**Pull request closed without merging**
